image: alpine

default:
  before_script:
    - apk update
    - apk upgrade

stages:
  - build
  - test

compile_example:
  stage: build
  script:
    - apk add --no-cache perl gnupg curl
    # Download TeX Live installation script.
    - mkdir install
    - wget -c http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -O - | tar -xz -C install
    # Install TeX Live using predefine installation profile.
    - perl install/install-tl*/install-tl --profile=tests/texlive.profile --repository=https://ctan.net/systems/texlive/tlnet/
    # Add folder of TeX-related executables to system path.
    - export PATH=$PATH:/usr/local/texlive/2023/bin/x86_64-linuxmusl
    # Install additional TeX packages.
    - tlmgr install ccicons csquotes datatool datetime2 datetime2-english doclicense
      enumitem glossaries glossaries-english hypdoc idxlayout ifoddpage mfirstuc
      morewrites multirow nag pdfx relsize todonotes xfor xifthen xmpincl xstring
    # Ensure creation of the naustrian language.
    - tlmgr install babel-german datetime2-german glossaries-german
    - sh ./build-all.sh # Build document class and example file.
  rules:
    - when: always
  artifacts:
    paths:
      - example.pdf # Output the compiled example file.
      - example.log # Output the compilation log for debugging.
    expire_in: 1 year

compare_with_reference:
  stage: test
  script:
    - apk add --no-cache poppler-utils imagemagick imagemagick-pdf # Install comparison tools.
    # Count the pages of the compiled example file and its reference.
    - pagecount=$(pdfinfo example.pdf | grep Pages | awk '{print $2}')
    - pagecount_ref=$(pdfinfo example-ref.pdf | grep Pages | awk '{print $2}')
    # Compare page counts and report error if they do not match.
    - if [ "$pagecount" -ne "$pagecount_ref" ]; then
        printf '%s\n' "Page count of generated example file does not match reference" >&2 &&
        exit 1;
      else
        printf '%s\n' "Page count of generated example file matches reference" >&2;
      fi
    # Generate per-page difference images between the example file and its reference.
    - "magick example.pdf null: example-ref.pdf
       -compose difference -layers composite -channel a -separate
       tests/diff_%d.png"
    # Measure per-page differences between the example file and its reference.
    - "magick example.pdf null: example-ref.pdf
       -compose difference -layers composite -channel a -separate -precision 12
       -format %[fx:mean]\\\\n info: > tests/differences.dat"
    # Get the largest difference across all pages.
    - difference=$(sort -g tests/differences.dat | tail -n 1 | awk '{ printf "%.20f", $1 }')
    # Check for non-zero differences and report error if difference detected.
    - if [ 1 -eq "$(echo "${difference} > 0" | bc -l)" ]; then
        printf '%s\n' "Generated example file does not match reference" >&2 &&
        exit 1;
      else
        printf '%s\n' "Generated example file matches reference" >&2;
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - when: always
  artifacts:
    paths:
      - tests/*.png # Output the difference images for debugging.
      - tests/*.dat # Output the per-page differences for debugging.
    when: always
    expire_in: 1 year

check_pdf_a:
  stage: test
  script:
    - apk add --no-cache openjdk11 # Install Java platform.
    # Download veraPDF installer and install it.
    - wget -c https://software.verapdf.org/rel/verapdf-installer.zip
    - unzip verapdf-installer.zip
    - (echo "1"; sleep 1; echo "/root/verapdf"; sleep 1; echo "O"; sleep 1;
       echo "1"; sleep 1;echo "Y"; sleep 1; echo "N"; sleep 1; echo "N"; sleep 1; echo "1") |
      sh ./verapdf-*/verapdf-install # Enter choices for the interactive menu of the Java installer.
    # Validate the generated PDF.
    - validation=$(/root/verapdf/verapdf --format text example.pdf)
    # Check the validation result.
    - if [[ "$validation" == PASS* ]]; then
        printf '%s\n' "Generated example file conforms to the PDF/A standard" >&2;
      else
        printf '%s\n' "Generated example file does not conforms to the PDF/A standard" >&2 &&
        exit 1;
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - when: always
